// 'use client'
import ConfigureAmplifyClientSide from '@/app/shared/components/ConfigureAmplify'
import { CategoryStoreProvider } from '@/app/shared/providers/CategoryStoreProvider'
import '@aws-amplify/ui-react/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Alerts from './components/Alerts'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="es"
      style={{
        overflow: 'hidden'
      }}
    >
      <body className={inter.className}>
        <CategoryStoreProvider>
          <ConfigureAmplifyClientSide />
          {children}
          <Alerts />
        </CategoryStoreProvider>
      </body>
    </html>
  )
}
